### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by RicardoXV** [l1ving/youtube-dl#13] opened 2020-10-29 20:58 UTC
Hi,

I dont know if you can help with this, but i got a problem with the current youtube-dl.exe. Im using it for a discord musicbot called sinusbot. recently the playback of music just stopped working, tho the bot logs show everything is okay. probably it has something to do with the dmca situation. so i thought an more recent version of the youtube-dl.exe would fix it. since i couldnt find any newer version of the .exe than the one i already had from the official 09.20 release, i downloaded this sourcecode today and compiled it myself with pyinstaller into an .exe. my problem is that the outputted youtube-dl.exe does not work too. did i forget something or am i doing something wrong or is there something special i have to consider when compiling the .exe?

Hope you can help me.

**Comment by l1ving** [comment] 2020-10-29 21:03
I'd need the error message in order to help.

**Comment by RicardoXV** [comment] 2020-10-29 21:20
so here is the error output when i manually execute the selfcompiled .exe:

`ERROR: uI8yxcdbAqA: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "youtube_dl\extractor\common.py", line 532, in extract
  File "youtube_dl\extractor\youtube.py", line 1778, in _real_extract
youtube_dl.utils.ExtractorError: uI8yxcdbAqA: YouTube said: Unable to extract video data`

**Comment by l1ving** [comment] 2020-10-29 21:22
Does this work on other videos?

**Comment by RicardoXV** [comment] 2020-10-29 21:25
yes works with other sources like soundcloud

**Comment by l1ving** [comment] 2020-10-29 21:31
I meant other youtube videos

**Comment by RicardoXV** [comment] 2020-10-29 21:35
tried another video with the output:

`ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "urllib\request.py", line 523, in open
  File "urllib\request.py", line 632, in http_response
  File "urllib\request.py", line 561, in error
  File "urllib\request.py", line 494, in _call_chain
  File "urllib\request.py", line 641, in http_error_default`

**Comment by l1ving** [comment] 2020-10-29 21:38
> Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by RicardoXV** [comment] 2020-10-29 21:41
i did use the --verbose flag, that response is wrong somehow^^

**Comment by l1ving** [comment] 2020-10-29 21:47
Oh, my bad. Yea, I can't help you here, you'd have to wait for someone else who knows more about Python.

**Comment by RicardoXV** [comment] 2020-10-29 21:49
humm okay thx anyway, hope someone knows how to solve this

**Comment by RicardoXV** [comment] 2020-10-30 12:50
I've been researching a bit and found out that the "http error 429 Too Many Requests" means that my ip has been softbanned. I havent found out how to unban or avoid a softban except by using a vpn/proxy. but since i cant run a vpn on the host cuz there are running other services that need to stay up under the softbanned ip and i cant set a proxy flag for the youtube-dl.exe manually either cuz the sinusbot controls which flags are set and i have no idea if it is possible to manually add any flags to the deafault ones, i dont know how to solve this. If you have any ideas on that, it would be the way to the solution of the problem

**Comment by l1ving** [comment] 2020-10-30 13:51
No, sorry. I haven't really used windows, I know on Linux you can redirect traffic for a process by port.

**Comment by ffabio81** [comment] 2020-10-30 14:44
Hi,

1. "ERROR: uI8yxcdbAqA: YouTube said: Unable to extract video data Traceback..."
2. "ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests..."

These are two different problems:
1. it is a bug related to extraction very similar to bug "Unable to extract JS player URL" just solved. With the last repo version try to remove cache on Youtube-dl command (--rm-cache-dir) and retry.

2. imho it's not a bug, it is an error related to a softban made by the provider (es. YouTube) due to too many request sent.

**Comment by RicardoXV** [comment] 2020-10-30 15:10
A bit to early too close I guess^^.
@ffabio81 
About 1: I did remove the cache with the --rm-cache-dir flag and that same video still outputted the same ERROR.
About 2: Ye, any ideas on how to solve that? Found that out recently and mentioned some points on that on my last reply.

Thanks for clarifying ERROR 1, didnt know that means it really IS an actual youtube-dl problem^^.

**Comment by ffabio81** [comment] 2020-10-30 16:35
Hi @RicardoXV ,

1. Sorry, I tested again and the bug is still present. So the bug tittled "Unable to extract JS player URL" probably needs to be reopened...
2. I use a VPN service to solve the problem

**Comment by l1ving** [comment] 2020-10-30 16:39
> and the bug is still present

How did you download the version of youtube-dl which you're using?

**Comment by ZenulAbidin** [comment] 2020-10-30 21:24
@RicardoXV , usually when youtube returns a 429 HTTP error it means that you were downloading a large enough video too fast from it. Happened to me a couple times with the original youtube-dl program in the past and I had to wait for some time before I could download again.

But since you mentioned a music bot is the one calling youtube-dl, I think your users might be calling it too fast, and this downloads a lot of audio from Youtube too quickly. You can try passing the `-r <bytes>` option to download a maximum of *<bytes>* per second. I don't think there's anything that youtube-dl can do to fix this, this is more of a user error than a bug in the code.

`--verbose` logs were not detailed enough to help with this.

**Comment by l1ving** [comment] 2020-10-31 01:58
I have confirmed No 1 is fixed with the same URL you provided in the latest release.

**Closed by l1ving** 2020-10-31 01:58 UTC
Labels: bug

**Comment by RicardoXV** [comment] 2020-10-31 16:15
I opened a Thread in the Sinusbot Forum too, where a dev could tell me that when sinusbot runs the youtube-dl.exe it also looks into these locations: https://manpages.debian.org/stretch/youtube-dl/youtube-dl.1.en.html#:~:text=config%2Fyoutube%2Ddl%2Fconfig.,conf. I just created the mentioned youtube-dl directory with the config.txt and added the --proxy flag. Now youtube-dl.exe automatically runs these flags additional to the sinusbot defaults. So No. 2 is solved for me too.

@ZenulAbidin thats a good point what would you suggest how many bytes are reasonable for live enqueing
